name: babysitterapp
description: "A collaborative babysitter mobile app for the final project in it415."

publish_to: 'none' 

version: 1.0.101+1

environment:
 sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.3.3
  page_transition: ^2.1.0
  flutter_animate: ^4.3.0
  flutter_launcher_icons: ^0.14.1
  fluentui_system_icons: ^1.1.257
  flutter_dotenv: ^5.1.0
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  cloud_firestore: ^5.4.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  hooks_riverpod: ^2.5.4
  google_sign_in: ^6.2.1
  file_picker: ^8.1.3
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^13.0.1
  permission_handler: ^11.2.1
  flutter_screenutil: ^5.9.3
  toastification: ^2.3.0
  shared_preferences: ^2.3.3
  board_datetime_picker: ^2.1.5
  geocoding: ^3.0.0
  fl_chart: ^0.69.0
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  form_builder_file_picker: ^4.2.0
  form_builder_image_picker: ^4.1.0
  form_builder_phone_field: ^2.0.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  dio: ^5.7.0

# dart run build_runner build --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.8
  build_runner: ^2.4.13
  husky: ^0.1.7
  dartz: ^0.10.1
  test: ^1.25.7
  stack_trace: ^1.11.1
  logger: ^2.5.0
  
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"

# dart run build_runner build
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env 

fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand_Bold_Oblique.otf
        - asset: assets/fonts/Quicksand_Bold.otf
        - weight: 700
    - family: Quicksan_Book
      fonts:
        - asset: assets/fonts/Quicksand_Book_Oblique.otf
        - asset: assets/fonts/Quicksand_Book.otf
    - family: Nexa-ExtraLight
      fonts:
        - asset: assets/fonts/Nexa-ExtraLight.ttf
        - weight: 700
    - family: Nexa-Heavy
      fonts:
        - asset: assets/fonts/Nexa-Heavy.ttf
        - weight: 900
